// The words the package itself says, in Croatian, which is where a word is
// written first. A module says only what it alone knows; saying one of these
// again throws at boot.

export const hr = {
	'about.suite': 'OPUS je kućna zbirka glazbe, filmova, serija, web-videozapisa i fotografija u tri modula. Library odlučuje što vrijedi imati, što se računa kao posjedovanje i kako se datoteka zove; Downloads to nabavlja iz svih izvora iza jednog sučelja; Player to pušta na uređaju na kojem radi: televizoru, mobitelu ili DAC-u. Svaki modul je zasebna aplikacija s vlastitom adresom i vlastitim izdanjem, a dijele prijavu, izgled i jezik.',
	'account.changed': 'Zaporka je promijenjena.',
	'account.current': 'Trenutna zaporka',
	'account.err.blank': 'Ispunite obje zaporke.',
	'account.err.mismatch': 'Nove zaporke se ne podudaraju.',
	'account.err.rejected': 'Trenutna zaporka nije točna.',
	'account.logout': 'Odjava',
	'account.new': 'Nova zaporka',
	'account.passkeyAdd': 'Dodaj pristupni ključ',
	'account.passkeyAdded': 'Pristupni ključ je dodan. Njime se prijavljujete u Library, Player i Downloads.',
	'account.passkeyConfirm': 'Za dodavanje ključa upišite trenutnu zaporku.',
	'account.passkeyContinue': 'Nastavi',
	'account.passkeyExists': 'Ovaj uređaj već ima pristupni ključ za OPUS.',
	'account.passkeyFailed': 'Pristupni ključ nije dodan.',
	'account.passkeyHint': 'Pristupni ključ otvara OPUS otiskom prsta, licem ili PIN-om uređaja, bez zaporke.',
	'account.passkeyMade': 'Dodan {when}',
	'account.passkeyNone': 'Još nema pristupnih ključeva.',
	'account.passkeyRemove': 'Ukloni',
	'account.passkeyUsed': 'Zadnja prijava {when}',
	'account.passkeys': 'Pristupni ključevi',
	'account.password': 'Zaporka',
	'account.repeat': 'Ponovite novu zaporku',
	'account.token': 'Tokeni modula',
	'account.tokenFor.cameras': 'Kamere (BABA)',
	'account.tokenFor.downloads': 'Downloads',
	'account.tokenFor.house': 'Kućna automatika (DIDA)',
	'account.tokenFor.library': 'Library',
	'account.tokenFor.player': 'Player',
	'account.tokenIssued': 'Novi token vrijedi odmah, a stari više ne otvara ništa — upišite ga u modul kojemu pripada.',
	'account.tokenNew': 'Izdaj novi token',
	'account.tokenNone': 'Token još nije izdan.',
	'account.tokenShow': 'Prikaži',
	'account.yours': 'Vaš račun',
	'common.loading': 'Učitavam…',
	'devices.asking': 'Uređaj koji čeka',
	'devices.askingNow': 'traži pristup — upišite kôd s njegovog zaslona',
	'devices.code': 'Kôd sa zaslona',
	'devices.err.blank': 'Upišite kôd sa zaslona uređaja.',
	'devices.err.noCode': 'Taj kôd ne čeka odobrenje — istekao je ili je pogrešno prepisan.',
	'devices.hint': 'Uređaj prikazuje kôd na svom zaslonu. Prepišite ga ovdje i dajte uređaju ime po kojem ćete ga prepoznati.',
	'devices.lastSeen': 'zadnji put viđen {when}',
	'devices.letIn': 'Odobri uređaj',
	'devices.letInBy': 'pristup odobrio {who}',
	'devices.name': 'Naziv uređaja',
	'devices.none': 'Nijedan uređaj još nema pristup.',
	'devices.notCollected': 'odobren, još nije preuzeo pristup',
	'devices.takeBack': 'Oduzmi pristup',
	'devices.title': 'Uređaji',
	'devices.wasLetIn': 'Uređaj {name} ima pristup.',
	'head.less': 'Prikaži manje',
	'head.more': 'Prikaži više',
	'login.failed': 'Neispravno korisničko ime ili zaporka.',
	'login.missing': 'Upišite korisničko ime i zaporku.',
	'login.passkey': 'Prijava pristupnim ključem',
	'login.passkeyFailed': 'Pristupni ključ nije prihvaćen.',
	'login.password': 'Zaporka',
	'login.submit': 'Prijava',
	'login.tooMany': 'Previše neuspjelih pokušaja. Pokušajte ponovno za nekoliko minuta.',
	'login.unavailable': 'Prijava trenutno nije moguća.',
	'login.username': 'Korisničko ime',
	'login.working': 'Prijavljujem…',
	'people.add': 'Dodaj osobu',
	'people.disable': 'Onemogući',
	'people.disabled': 'onemogućen',
	'people.display': 'Ime i prezime',
	'people.enable': 'Omogući',
	'people.err.blank': 'Osoba treba korisničko ime i zaporku.',
	'people.err.mismatch': 'Zaporke se ne podudaraju.',
	'people.err.notAdmin': 'Popis osoba može mijenjati samo administrator.',
	'people.err.refused': 'Instalacija mora imati barem jednog administratora, a sebe ne možete ukloniti.',
	'people.err.short': 'Zaporka mora imati barem 8 znakova — iz nje se izvodi ključ trezora.',
	'people.name': 'Korisničko ime',
	'people.newPassword': 'Nova zaporka',
	'people.password': 'Zaporka',
	'people.remove': 'Ukloni',
	'people.repeat': 'Ponovite zaporku',
	'people.reset': 'Postavi zaporku',
	'people.role': 'Razina',
	'people.role.admin': 'administrator',
	'people.role.guest': 'gost',
	'people.role.user': 'korisnik',
	'people.title': 'Ljudi',
	'people.wasAdded': 'Osoba {name} je dodana.',
	'people.you': 'vi',
	'photos.count.few': '{n} fotografije',
	'photos.count.many': '{n} fotografija',
	'photos.count.one': '{n} fotografija',
	'photos.discard': 'Obriši fotografiju',
	'photos.download': 'Preuzmi original',
	'photos.empty': 'Ovdje još nema fotografija.',
	'photos.jump': 'Skoči na razdoblje',
	'photos.next': 'Sljedeća',
	'photos.notThisPerson': 'Nije ova osoba — skida ime s ovog lica',
	'photos.photo': 'Fotografija',
	'photos.placeSpread.few': 'upisano na {n} fotografije',
	'photos.placeSpread.many': 'upisano na {n} fotografija',
	'photos.placeSpread.one': 'upisano na {n} fotografiju',
	'photos.prev': 'Prethodna',
	'photos.regrouping': 'Lica se upravo ponovno grupiraju. Pokušajte ponovno za nekoliko minuta.',
	'photos.search.hint': 'Osoba, mjesto ili vrijeme, npr. Ana Split ljeto 2019',
	'photos.search.none': 'Nijedna fotografija ne odgovara pretrazi.',
	'photos.search.unread': 'Ne prepoznajem: {words}',
	'photos.thisOne': 'samo ova',
	'photos.turn': 'Zakreni',
	'photos.undated.n': '{n} bez datuma',
	'photos.unknownFace': 'Neimenovano lice',
	'photos.unknownFaces': 'još lica: {n}',
	'photos.unnamedPlace': '+ ime mjesta',
	'photos.unreadable': 'Ovu fotografiju nije moguće prikazati',
	'photos.whereAsk': 'Gdje je snimljeno?',
	'photos.whereUnknown': '+ mjesto',
	'photos.wholeDay': 'cijeli dan',
	'prefs.language': 'Jezik',
	'prefs.theme': 'Tema',
	'theme.pick.dark': 'Tamna',
	'theme.pick.light': 'Svijetla',
	'theme.pick.system': 'Prema sustavu',
} as const;
